<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<SignAssembly>true</SignAssembly>
	<AssemblyOriginatorKeyFile>Sooda.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="CDIL\Templates\ClassField.cdil" />
    <None Remove="CDIL\Templates\DatabaseSchema.cdil" />
    <None Remove="CDIL\Templates\Factory.cdil" />
    <None Remove="CDIL\Templates\ListWrapper.cdil" />
    <None Remove="CDIL\Templates\Loader.cdil" />
    <None Remove="CDIL\Templates\NullableTypedWrapper.cdil" />
    <None Remove="CDIL\Templates\ProxyInterface.cdil" />
    <None Remove="CDIL\Templates\ProxyInterfaceFactory.cdil" />
    <None Remove="CDIL\Templates\Skeleton.cdil" />
    <None Remove="CDIL\Templates\Stub.cdil" />
    <None Remove="CDIL\Templates\TypedCollectionWrapper.cdil" />
    <None Remove="CDIL\Templates\TypedWrapper.cdil" />
    <None Remove="SoodaProject.xsd" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="CDIL\Templates\ClassField.cdil" />
    <EmbeddedResource Include="CDIL\Templates\DatabaseSchema.cdil" />
    <EmbeddedResource Include="CDIL\Templates\Factory.cdil" />
    <EmbeddedResource Include="CDIL\Templates\ListWrapper.cdil" />
    <EmbeddedResource Include="CDIL\Templates\Loader.cdil" />
    <EmbeddedResource Include="CDIL\Templates\NullableTypedWrapper.cdil" />
    <EmbeddedResource Include="CDIL\Templates\ProxyInterface.cdil" />
    <EmbeddedResource Include="CDIL\Templates\ProxyInterfaceFactory.cdil" />
    <EmbeddedResource Include="CDIL\Templates\Skeleton.cdil" />
    <EmbeddedResource Include="CDIL\Templates\Stub.cdil" />
    <EmbeddedResource Include="CDIL\Templates\TypedCollectionWrapper.cdil" />
    <EmbeddedResource Include="CDIL\Templates\TypedWrapper.cdil" />
    <EmbeddedResource Include="SoodaProject.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CodeDom" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sooda\Sooda.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="SoodaProject.cs">
      <DependentUpon>SoodaProject.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
