<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<SignAssembly>true</SignAssembly>
	<AssemblyOriginatorKeyFile>Sooda.snk</AssemblyOriginatorKeyFile>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<IncludeSymbols>True</IncludeSymbols>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sooda.CodeGen\Sooda.CodeGen.csproj" />
  </ItemGroup>

</Project>
