<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sooda\Sooda.csproj" />
  </ItemGroup>
  
  <PropertyGroup>
   <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
   <SignAssembly>true</SignAssembly>
   <AssemblyOriginatorKeyFile>Sooda.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

</Project>
