<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <SignAssembly>true</SignAssembly>
        <DelaySign>false</DelaySign>
        <AssemblyOriginatorKeyFile>Sooda.snk</AssemblyOriginatorKeyFile>

        <PackageId>Sooda</PackageId>
        <PackageVersion>1.0.0</PackageVersion>

        <Authors>Jarosław Kowalski, Piotr Fusik, Maciej Figatowski, Marcin Krupiński, Rafał Gwizdała, Damian Załęcki, Maciej Nowak, &amp; others</Authors>
        <Company>Sooda ORM</Company>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <Description>
            Sooda is an object-to-relational mapping (O/R Mapping) software for the .NET environment. It lets you automatically generate an object-oriented data access layer (DAL) for your application. Instead of writing SQL code, you can now focus on writing business rules in object-oriented .NET languages.

            Sooda is an open source software distributed under the terms of the BSD license.
        </Description>
        <PackageTags>orm sql object relational mapping data access repository</PackageTags>
        <TargetFrameworks>netstandard2.0</TargetFrameworks>
        <RepositoryUrl>https://github.com/sooda-orm/sooda.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <IncludeSymbols>True</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Schema\SoodaSchema.xsd">
            <SubType>Designer</SubType>
        </EmbeddedResource>
        <None Include="QL\TypedWrappers\makewrappers.pl" />
        <None Include="Schema\SoodaSchema.xsx">
            <DependentUpon>SoodaSchema.xsd</DependentUpon>
        </None>
    </ItemGroup>

</Project>
